"""Ghost-PM Configuration Loader.

Loads config from multiple sources with this priority:
1. Environment variables (highest)
2. .ghost/config.json (room-specific, auto-generated by ghostpm connect)
3. Built-in defaults (Supabase credentials baked in)
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # dotenv is optional — credentials are built-in


# ── Built-in Supabase credentials ────────────────────
# These are baked into the package so users don't need to configure anything.
# The Supabase project is shared across all Ghost-PM users.
GHOST_SUPABASE_URL = "https://yhzbksniwuwqrdfozrmi.supabase.co"
GHOST_SUPABASE_KEY = "sb_publishable_LiIKpOv77TJ8itK7wRk0_g_rZ9YqZIm"


def _find_ghost_dir() -> Path | None:
    """Walk up from cwd to find .ghost/ directory."""
    current = Path.cwd()
    for parent in [current, *current.parents]:
        ghost_dir = parent / ".ghost"
        if ghost_dir.is_dir():
            return ghost_dir
    return None

def _load_ghost_config() -> dict:
    """Load .ghost/config.json if it exists."""
    ghost_dir = _find_ghost_dir()
    if ghost_dir is None:
        return {}
    config_path = ghost_dir / "config.json"
    if config_path.exists():
        with open(config_path, "r") as f:
            return json.load(f)
    return {}

@dataclass
class GhostConfig:
    """Central configuration for Ghost-PM."""
    # Supabase (built-in defaults)
    supabase_url: str = GHOST_SUPABASE_URL
    supabase_key: str = GHOST_SUPABASE_KEY

    # LLM
    gemini_api_key: str = ""
    openai_api_key: str = ""
    model: str = "google:gemini-2.0-flash"

    # Room
    room_id: str = ""
    member_name: str = ""

    # Paths
    ghost_dir: Path = field(default_factory=lambda: Path.cwd() / ".ghost")
    project_root: Path = field(default_factory=Path.cwd)

    @classmethod
    def load(cls) -> GhostConfig:
        """Load configuration from all sources."""
        ghost_config = _load_ghost_config()
        ghost_dir = _find_ghost_dir() or Path.cwd() / ".ghost"

        return cls(
            supabase_url=os.getenv("SUPABASE_URL", ghost_config.get("supabase_url", GHOST_SUPABASE_URL)),
            supabase_key=os.getenv("SUPABASE_KEY", ghost_config.get("supabase_key", GHOST_SUPABASE_KEY)),
            gemini_api_key=os.getenv("GEMINI_API_KEY", ghost_config.get("gemini_api_key", "")),
            openai_api_key=os.getenv("OPENAI_API_KEY", ghost_config.get("openai_api_key", "")),
            model=os.getenv("GHOST_MODEL", ghost_config.get("model", "google:gemini-2.0-flash")),
            room_id=os.getenv("GHOST_ROOM_ID", ghost_config.get("room_id", "")),
            member_name=os.getenv("GHOST_MEMBER_NAME", ghost_config.get("member_name", "")),
            ghost_dir=ghost_dir,
            project_root=ghost_dir.parent if ghost_dir.exists() else Path.cwd(),
        )

    def save_ghost_config(self) -> None:
        """Persist room-specific config to .ghost/config.json."""
        self.ghost_dir.mkdir(parents=True, exist_ok=True)
        config_data = {
            "supabase_url": self.supabase_url,
            "supabase_key": self.supabase_key,
            "room_id": self.room_id,
            "member_name": self.member_name,
            "model": self.model,
            "gemini_api_key": self.gemini_api_key,
        }
        config_path = self.ghost_dir / "config.json"
        with open(config_path, "w") as f:
            json.dump(config_data, f, indent=2)

    @property
    def state_path(self) -> Path:
        return self.ghost_dir / "state.json"

    @property
    def graph_path(self) -> Path:
        return self.ghost_dir / "graph.json"

    @property
    def scope_log_path(self) -> Path:
        return self.ghost_dir / "scope_log.jsonl"

    @property
    def has_supabase(self) -> bool:
        return bool(self.supabase_url and self.supabase_key)

    @property
    def has_llm(self) -> bool:
        return bool(self.gemini_api_key or self.openai_api_key)

    @property
    def llm_model_string(self) -> str:
        """Return the pydantic-ai model string based on available keys."""
        if self.gemini_api_key:
            return self.model if self.model.startswith("google:") else "google:gemini-2.0-flash"
        if self.openai_api_key:
            return "openai:gpt-4o"
        return self.model
