"""Ghost-PM Configuration Loader.

Loads config from multiple sources with this priority:
1. Environment variables (highest)
2. .ghost/config.json (team-specific, auto-generated by ghostpm join)
3. Built-in defaults (Supabase credentials baked in)
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # dotenv is optional — credentials are built-in


# ── Built-in Supabase credentials ────────────────────
# Baked into the package so users don't need to configure anything.
GHOST_SUPABASE_URL = "https://yhzbksniwuwqrdfozrmi.supabase.co"
GHOST_SUPABASE_KEY = "sb_publishable_LiIKpOv77TJ8itK7wRk0_g_rZ9YqZIm"

# ── Main UI URL (updated after deployment) ───────────
GHOST_UI_URL = "https://ghost-pm.vercel.app"


def _find_ghost_dir() -> Path | None:
    """Walk up from cwd to find .ghost/ directory."""
    current = Path.cwd()
    for parent in [current, *current.parents]:
        ghost_dir = parent / ".ghost"
        if ghost_dir.is_dir():
            return ghost_dir
    return None

def _load_ghost_config() -> dict:
    """Load .ghost/config.json if it exists."""
    ghost_dir = _find_ghost_dir()
    if ghost_dir is None:
        return {}
    config_path = ghost_dir / "config.json"
    if config_path.exists():
        with open(config_path, "r") as f:
            return json.load(f)
    return {}

@dataclass
class GhostConfig:
    """Central configuration for Ghost-PM."""
    # Supabase (built-in defaults)
    supabase_url: str = GHOST_SUPABASE_URL
    supabase_key: str = GHOST_SUPABASE_KEY

    # LLM
    gemini_api_key: str = ""
    openai_api_key: str = ""
    model: str = "gemini-3.6-flash"

    # Team (unified with teammate's schema)
    team_id: str = ""          # UUID from teams table
    team_code: str = ""        # Human-readable join code
    member_name: str = ""      # Display name in terminal
    user_id: str = ""          # Supabase auth.users UUID

    # Auth
    access_token: str = ""     # Supabase JWT
    refresh_token: str = ""    # Supabase refresh token

    # URLs
    ui_url: str = GHOST_UI_URL

    # Paths
    ghost_dir: Path = field(default_factory=lambda: Path.cwd() / ".ghost")
    project_root: Path = field(default_factory=Path.cwd)

    # Legacy compat
    @property
    def room_id(self) -> str:
        return self.team_code or self.team_id

    @classmethod
    def load(cls) -> GhostConfig:
        """Load configuration from all sources."""
        ghost_config = _load_ghost_config()
        ghost_dir = _find_ghost_dir() or Path.cwd() / ".ghost"

        return cls(
            supabase_url=os.getenv("SUPABASE_URL", ghost_config.get("supabase_url", GHOST_SUPABASE_URL)),
            supabase_key=os.getenv("SUPABASE_KEY", ghost_config.get("supabase_key", GHOST_SUPABASE_KEY)),
            gemini_api_key=os.getenv("GEMINI_API_KEY", ghost_config.get("gemini_api_key", "")),
            openai_api_key=os.getenv("OPENAI_API_KEY", ghost_config.get("openai_api_key", "")),
            model=os.getenv("GHOST_MODEL", ghost_config.get("model", "gemini-3.6-flash")),
            team_id=ghost_config.get("team_id", ""),
            team_code=ghost_config.get("team_code", ghost_config.get("room_id", "")),
            member_name=os.getenv("GHOST_MEMBER_NAME", ghost_config.get("member_name", "")),
            user_id=ghost_config.get("user_id", ""),
            access_token=ghost_config.get("access_token", ""),
            refresh_token=ghost_config.get("refresh_token", ""),
            ui_url=ghost_config.get("ui_url", GHOST_UI_URL),
            ghost_dir=ghost_dir,
            project_root=ghost_dir.parent if ghost_dir.exists() else Path.cwd(),
        )

    def save_ghost_config(self) -> None:
        """Persist team-specific config to .ghost/config.json."""
        self.ghost_dir.mkdir(parents=True, exist_ok=True)
        config_data = {
            "supabase_url": self.supabase_url,
            "supabase_key": self.supabase_key,
            "team_id": self.team_id,
            "team_code": self.team_code,
            "member_name": self.member_name,
            "user_id": self.user_id,
            "model": self.model,
            "gemini_api_key": self.gemini_api_key,
            "access_token": self.access_token,
            "refresh_token": self.refresh_token,
            "ui_url": self.ui_url,
        }
        config_path = self.ghost_dir / "config.json"
        with open(config_path, "w") as f:
            json.dump(config_data, f, indent=2)

    @property
    def state_path(self) -> Path:
        return self.ghost_dir / "state.json"

    @property
    def graph_path(self) -> Path:
        return self.ghost_dir / "graph.json"

    @property
    def scope_log_path(self) -> Path:
        return self.ghost_dir / "scope_log.jsonl"

    @property
    def session_path(self) -> Path:
        return self.ghost_dir / "session.json"

    @property
    def has_supabase(self) -> bool:
        return bool(self.supabase_url and self.supabase_key)

    @property
    def has_llm(self) -> bool:
        return bool(self.gemini_api_key or self.openai_api_key)

    @property
    def has_auth(self) -> bool:
        return bool(self.access_token)

    @property
    def llm_model_string(self) -> str:
        """Return the pydantic-ai model string based on available keys."""
        if self.gemini_api_key:
            return self.model if self.model.startswith("google:") else "google:gemini-3.6-flash"
        if self.openai_api_key:
            return "openai:gpt-4o"
        return self.model
