"""Ghost-PM State Models.

Pydantic models defining the complete project state.
state.json is the ONLY thing the LLM reads — never raw source code.
It's incrementally updated by git hooks, the daemon, and graphify output.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field


# ──────────────────────────────────────────────────────────────
# Graph-derived models (populated from graphify's graph.json)
# ──────────────────────────────────────────────────────────────


class GraphNode(BaseModel):
    """A node in the code graph — could be a file, function, class, etc."""

    name: str
    node_type: Literal["file", "function", "class", "module", "variable", "other"] = "other"
    file_path: str = ""
    language: str = ""
    status: Literal["stub", "in_progress", "implemented", "tested", "broken", "unknown"] = "unknown"
    line_start: int | None = None
    line_end: int | None = None
    connections: int = 0  # Number of edges connected to this node
    community: str = ""  # Which community/cluster this belongs to
    description: str = ""  # LLM-generated or extracted docstring


class GraphEdge(BaseModel):
    """A relationship between two nodes."""

    source: str
    target: str
    edge_type: Literal["calls", "imports", "inherits", "depends_on", "owns", "other"] = "other"
    confidence: Literal["extracted", "inferred"] = "extracted"


class GraphCommunity(BaseModel):
    """A cluster of related code detected by graphify."""

    name: str
    files: list[str] = Field(default_factory=list)
    functions: int = 0
    description: str = ""


class GodNode(BaseModel):
    """A heavily-connected node — potential risk/refactor candidate."""

    name: str
    file_path: str = ""
    connections: int = 0
    risk: Literal["low", "medium", "high"] = "low"


class CodeGraphSummary(BaseModel):
    """Compact summary of the entire codebase graph."""

    total_nodes: int = 0
    total_edges: int = 0
    total_functions: int = 0
    total_files: int = 0
    communities: list[GraphCommunity] = Field(default_factory=list)
    god_nodes: list[GodNode] = Field(default_factory=list)
    function_statuses: dict[str, int] = Field(
        default_factory=lambda: {
            "stub": 0,
            "in_progress": 0,
            "implemented": 0,
            "tested": 0,
            "broken": 0,
            "unknown": 0,
        }
    )
    last_updated: datetime = Field(default_factory=datetime.now)


# ──────────────────────────────────────────────────────────────
# File tracking
# ──────────────────────────────────────────────────────────────


class FileRecord(BaseModel):
    """Tracks a single file in the project."""

    path: str
    language: str = ""
    functions_count: int = 0
    implemented_count: int = 0
    last_modifier: str = ""
    last_modified: datetime = Field(default_factory=datetime.now)
    status: Literal["new", "in_progress", "stable", "stale"] = "new"


# ──────────────────────────────────────────────────────────────
# Commit tracking
# ──────────────────────────────────────────────────────────────


class CommitSummary(BaseModel):
    """Compact commit record."""

    hash: str = ""
    message: str = ""
    author: str = ""
    files_changed: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.now)
    milestone_id: int | None = None
    scope_allowed: bool = True
    scope_reason: str = ""


# ──────────────────────────────────────────────────────────────
# Milestone tracking
# ──────────────────────────────────────────────────────────────


class MilestoneState(BaseModel):
    """State of a single milestone."""

    id: int
    name: str
    description: str = ""
    order_index: int = 0
    status: Literal["pending", "active", "completed"] = "pending"
    progress_percent: float = 0.0
    files_expected: list[str] = Field(default_factory=list)
    functions_expected: int = 0
    functions_implemented: int = 0
    commit_count: int = 0
    time_spent_minutes: int = 0
    started_at: datetime | None = None
    completed_at: datetime | None = None


# ──────────────────────────────────────────────────────────────
# Teammate tracking
# ──────────────────────────────────────────────────────────────


class Alert(BaseModel):
    """An alert generated by the monitoring system."""

    alert_type: Literal["info", "warning", "critical"] = "info"
    category: Literal[
        "scope_violation",
        "idle_warning",
        "time_box",
        "milestone_blocked",
        "god_node",
        "general",
    ] = "general"
    message: str
    timestamp: datetime = Field(default_factory=datetime.now)
    member_name: str = ""


class Suggestion(BaseModel):
    """A proactive suggestion from the advisor agent."""

    message: str
    priority: Literal["low", "medium", "high"] = "medium"
    category: str = "general"
    timestamp: datetime = Field(default_factory=datetime.now)


class TeamMemberSnapshot(BaseModel):
    """Current state of a team member."""

    member_name: str
    is_online: bool = True
    current_file: str = ""
    current_file_since: datetime = Field(default_factory=datetime.now)
    time_in_current_file_minutes: int = 0
    current_milestone_id: int | None = None
    total_commits: int = 0
    productive_minutes: int = 0
    idle_minutes: int = 0
    distraction_score: float = 0.0  # 0.0 = focused, 1.0 = distracted
    active_alerts: list[Alert] = Field(default_factory=list)
    last_active: datetime = Field(default_factory=datetime.now)


# ──────────────────────────────────────────────────────────────
# Top-level project state — THE state.json
# ──────────────────────────────────────────────────────────────


class ProjectState(BaseModel):
    """The COMPLETE project state.

    This is the ONLY file the LLM reads for context.
    Updated incrementally by git hooks, the daemon, and graphify.
    """

    # ── Identity ──
    room_id: str = ""
    project_name: str = ""
    description: str = ""
    tech_stack: list[str] = Field(default_factory=list)
    hackathon_start: datetime = Field(default_factory=datetime.now)
    hackathon_end: datetime = Field(default_factory=datetime.now)
    hours_remaining: float = 24.0

    # ── Milestones ──
    milestones: list[MilestoneState] = Field(default_factory=list)
    active_milestone_id: int | None = None
    overall_progress_percent: float = 0.0

    # ── Code Graph (from graphify) ──
    code_graph: CodeGraphSummary = Field(default_factory=CodeGraphSummary)

    # ── Files ──
    files: list[FileRecord] = Field(default_factory=list)

    # ── Recent Commits ──
    recent_commits: list[CommitSummary] = Field(default_factory=list)
    total_commits: int = 0
    scope_violations: int = 0

    # ── Team ──
    team: list[TeamMemberSnapshot] = Field(default_factory=list)

    # ── Alerts & Suggestions ──
    active_alerts: list[Alert] = Field(default_factory=list)
    suggestions: list[Suggestion] = Field(default_factory=list)

    # ── Meta ──
    last_updated: datetime = Field(default_factory=datetime.now)
    state_version: int = 0  # Increments on every update

    def save(self, path: Path) -> None:
        """Save state to disk."""
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            f.write(self.model_dump_json(indent=2))

    @classmethod
    def load(cls, path: Path) -> ProjectState:
        """Load state from disk. Returns empty state if file doesn't exist."""
        if not path.exists():
            return cls()
        with open(path, "r") as f:
            data = json.load(f)
        return cls.model_validate(data)

    def get_active_milestone(self) -> MilestoneState | None:
        """Get the currently active milestone."""
        for ms in self.milestones:
            if ms.id == self.active_milestone_id:
                return ms
        return None

    def get_member(self, name: str) -> TeamMemberSnapshot | None:
        """Get a team member by name."""
        for member in self.team:
            if member.member_name == name:
                return member
        return None

    def increment_version(self) -> None:
        """Bump state version and update timestamp."""
        self.state_version += 1
        self.last_updated = datetime.now()

    def update_hours_remaining(self) -> None:
        """Recalculate hours remaining until hackathon end."""
        now = datetime.now()
        end = self.hackathon_end
        # Strip timezone if present (Supabase returns offset-aware)
        if hasattr(end, 'tzinfo') and end.tzinfo is not None:
            end = end.replace(tzinfo=None)
        delta = end - now
        self.hours_remaining = max(0.0, delta.total_seconds() / 3600)

    def compute_overall_progress(self) -> None:
        """Recompute overall progress from milestones."""
        if not self.milestones:
            self.overall_progress_percent = 0.0
            return
        total = sum(ms.progress_percent for ms in self.milestones)
        self.overall_progress_percent = total / len(self.milestones)
